version: "3.7"

services:
  db:
    image: bitnami/postgresql:14
    environment:
      - POSTGRES_USER=jojo
      - POSTGRES_PASSWORD=jojo
      - POSTGRES_DB=jojo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/bitnami/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5    

  redis:
    image: bitnami/redis:7.0
    environment:
      REDIS_PASSWORD: "changeme123"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  db_data:
