# Continues deployment workflow to automatically
# build Docker image on tag 
name: CD

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      IS_CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Docker with buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Login to GitHub packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Build and publish images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/lazybytez/jojo-discord-bot:latest
