# Continues integration workflow to continuously check 
# code quality and run tests before merging PRs
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      IS_CI: true
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: make install

      - name: Run Go linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          skip-cache: true
          
  tests:
    runs-on: ubuntu-latest
    env:
      IS_CI: true
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: make install

      - name: Build project
        run: make build

      - name: Run Go tests
        run: go test -race -covermode=atomic -coverpkg=all -coverprofile=coverage.out ./...

      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v3
