# Continues deployment workflow to automatically
# build Docker image on tag 
name: Deploy Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: Production
    env:
      IS_CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker with buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_REGISTRY_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Login to GitHub packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/lazybytez/jojo-discord-bot
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Retrieve commit SHA
        id: commit_sha
        run: echo "::set-output name=short::$(git rev-parse --short HEAD)"

      - name: Build and publish public image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            app_version=${{ github.ref_name }}
            build_commit_sha=${{ steps.commit_sha.outputs.short }}

      - name: Publish image for production environment
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ghcr.io/lazybytez/jojo-discord-bot:latest
          dst: |
            registry.digitalocean.com/lazybytez/jojo-discord-bot:latest
