# Continues deployment workflow to automatically
# build Docker image on tag 
name: Deploy Edge

on:
  push:
    branches:
      - 'develop'

jobs:
  edge:
    runs-on: ubuntu-latest
    environment:
      name: Staging
    env:
      IS_CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker with buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to GitHub packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/lazybytez/jojo-discord-bot
          tags: |
            type=edge,branch=develop

      - name: Retrieve commit SHA
        id: commit_sha
        run: echo "::set-output name=short::$(git rev-parse --short HEAD)"

      - name: Build and publish images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            app_version=edge
            build_commit_sha=${{ steps.commit_sha.outputs.short }}
